# Generated by Django 3.0.1 on 2020-02-19 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2020, 2, 19, 16, 40, 40, 384376))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AddUser')),
            ],
        ),
    ]
